name: Moonshine SDK Installer

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: ["macos-latest"]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - uses: joshtynjala/setup-apache-flex-action@v2
      with:
        flex-version: "4.16.1"
        air-version: "33.1"
        accept-air-license: true
    - name: Build with Ant
      run: ant -noinput -buildfile 'MoonshineSDKInstaller/build/build.xml'
