# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Moonshine SDK Installer Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - uses: joshtynjala/setup-apache-flex-action@v1
      with:
        flex-version: "4.16.1"
    - name: Build with Ant
      run: ant -noinput -buildfile 'MoonshineSDKInstaller\build\build.xml' CompileSWF
