name: SUB - Build on Windows

on:
  workflow_dispatch:
    inputs:
      env:
        description: "An Environment"
        required: true
        type: choice
        options:
          - development
          - production
      version:
        description: "A Version"
        required: true
        type: string
      caching:
        description: "Use caching"
        required: true
        type: boolean
        default: false

  workflow_call:
    inputs:
      env:
        description: "An Environment"
        required: true
        type: string
      version:
        description: "A Version"
        required: true
        type: string
      caching:
        description: "Use caching"
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: "windows-latest"

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5

    - uses: joshtynjala/setup-apache-flex-action@v2
      with:
        flex-version: "4.16.1"
        air-version: "33.1"
        accept-air-license: true
        
    - name: Build with Ant        
      run: ant -buildfile 'MoonshineSDKInstaller/build/build.xml' all
